### ISSUE TITLE
Instructions to open the process console are unclear

### ISSUE THREAD

**Issue by JOE1994** [tock/book#3]
Hello :smile_cat: ,
In [this part](https://book.tockos.org/important_client.html#back-at-work-the-next-day) of the Tock OS book, I'm not sure how I should open the `process console`.

![image](https://user-images.githubusercontent.com/10286488/72214123-18a92d80-34ca-11ea-9bbf-a18aa22752b7.png)

In which step should I input `help` to open the `process console` ??
Typing `help` during the `tockloader listen` session doesn't seem to do anything..

Thank you!

**Comment by bradjc** [comment]
Running `help` in the tockloader listen terminal should do it. What hardware are you using and which version of the kernel are you running?

**Comment by JOE1994** [comment]
> Running `help` in the tockloader listen terminal should do it. What hardware are you using and which version of the kernel are you running?

I am using the `Hail` board, and I was using the kernel that was pre-installed with it.

I just updated the installed kernel with the following steps, and now the **tockloader listen terminal** works! Thank you :smile: 
1. cd tock/boards/hail
2. make program
